#!/bin/sh

echo "updating blur script"
cp /usr/bin/wpblur ./
echo "updating nvim configuration file"
cp ~/.config/nvim/init.vim ./config/nvim/
echo "updating snippets"
cp -r ~/.vim/snippets/ ./vim/

git add *
git commit -m "Update"
git push

