eval %sh{
    config_files="
        tmux.kak
        plugins/plug.kak/rc/plug.kak
        common.kak
        plugins.kak
        languages.kak
    "

    for file in $config_files; do
        echo source "$HOME/.config/kak/$file"
    done
}

