;;; early-init.el --- Early initialization -*- lexical-binding: t; buffer-read-only: t; no-byte-compile: t -*-

;; Author: Andrey Listopadov
;; Keywords: literate programming, Emacs configuration
;; Homepage: https://gitlab.com/andreyorst/dotfiles/-/tree/master/.config/emacs

;;; Commentary:
;; Emacs config.
;; This file was automatically generated by `org-babel-tangle'.
;; Do not change this file.  Main config is located in README.org at `user-emacs-directory'

;;; Code:

(defun aorst/wrap-obsolete (orig-fn &rest args)
  "Append extra argument to ARGS before calling ORIG-FN function."
  (if (cddr args)
      (apply orig-fn args)
    (apply orig-fn `(,@args "0"))))

(advice-add 'make-obsolete :around #'aorst/wrap-obsolete)
(advice-add 'make-obsolete-variable :around #'aorst/wrap-obsolete)
(advice-add 'define-obsolete-variable-alias :around #'aorst/wrap-obsolete)
(advice-add 'define-obsolete-function-alias :around #'aorst/wrap-obsolete)

(defvar aorst--gc-cons-threshold gc-cons-threshold)
(defvar aorst--gc-cons-percentage gc-cons-percentage)
(defvar aorst--file-name-handler-alist file-name-handler-alist)

(setq-default gc-cons-threshold 402653184
              gc-cons-percentage 0.6
              inhibit-compacting-font-caches t
              message-log-max 16384
              file-name-handler-alist nil)

(add-hook 'after-init-hook
          (defun aorst/restore-defaults-after-init ()
            (setq gc-cons-threshold aorst--gc-cons-threshold
                  gc-cons-percentage aorst--gc-cons-percentage
                  file-name-handler-alist aorst--file-name-handler-alist)))

(setq read-process-output-max (* 1024 1024 4)) ; 4mb

(when (featurep 'native-compile)
  (defvar native-comp-deferred-compilation)
  (setq native-comp-deferred-compilation t)
  (defvar native-comp-async-report-warnings-errors)
  (setq native-comp-async-report-warnings-errors nil))

(setq initial-frame-alist '((width . 170)
                            (height . 56)
                            (tool-bar-lines . 0)
                            (bottom-divider-width . 0)
                            (right-divider-width . 1))
      default-frame-alist initial-frame-alist
      frame-inhibit-implied-resize t
      x-gtk-resize-child-frames 'resize-mode)

(setq-default fringe-indicator-alist
              (assq-delete-all 'truncation fringe-indicator-alist))

(defvar straight-process-buffer)
(setq-default straight-process-buffer " *straight-process*")

(defvar straight-repository-branch)
(setq straight-repository-branch "develop")

(defvar straight-build-dir)
(setq straight-build-dir (format "build-%s" emacs-version))

(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(setq package-enable-at-startup nil)

(provide 'early-init)
;;; early-init.el ends here
