#!/bin/bash
error=0
cd ${1!substitute(getcwd(), '.*\vtests\/(\w+)$', '\1', "g")}
ref_file=${2:test_ref}
test_file=${3:test_file}
log=${4:log.txt}
touch $test_file
start_size=$(stat -c %s $test_file)
tmux_session=SimpleSnippetsTest

tmux new-session -d -n $tmux_session
tmux send-keys -t SimpleSnippetsTest "$1 -n -u ../testrc $test_file" enter "ggdGi/* test start */" ${0:key sequence} enter "/* test end */Qw"

while [[ $start_size == $(stat -c %s $test_file) ]]; do
    sleep 0.1
done

sha_ref=$(sha256sum $ref_file | sed -E "s/(\w+).*/\1/")
sha_res=$(sha256sum $test_file | sed -E "s/(\w+).*/\1/")

if [[ $sha_ref != $sha_res ]]; then
    echo "[ERR]: for test"
    mv $test_file $log
    error=1
else
    echo "[OK]: for test"
    rm $test_file
fi

tmux kill-window -t $tmux_session
exit $error

/home/aorst/.dotfiles/.vim/bundle/SimpleSnippets.vim/tests/continious_jumping
