#! /bin/sh

xfce4-panel &
sxhkd &
redshift -l 55.5:37.5 &
setxkbmap -layout us,ru -option grp:alt_shift_toggle &

bspc monitor -d ⚫ ⚫ ⚫ ⚫

bspc config border_width          4
bspc config window_gap           14
bspc config click_to_focus     true

bspc config presel_feedback_color '#7c7c80'
bspc config normal_border_color   '#404044'
bspc config focused_border_color  '#525256'
bspc config pointer_modifier mod4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Xfce4-appfinder state=floating
bspc rule -a Termite state=pseudo_tiled
bspc rule -a Gnome-terminal state=pseudo_tiled
bspc rule -a TelegramDesktop desktop='^2' state=pseudo_tiled
bspc rule -a Thunderbird desktop='^2' state=pseudo_tiled
bspc rule -a Screenkey manage=off
