#! /bin/sh

sxhkd &
setxkbmap -layout us,ru -option grp:alt_shift_toggle &

bspc monitor -d ⚫ ⚫ ⚫ ⚫ ⚫ ⚫ ⚫ ⚫ ⚫ ⚫

bspc config border_width          6
bspc config window_gap           24
bspc config click_to_focus     true

bspc config presel_feedback_color '#32302f'
bspc config normal_border_color   '#32302f'
bspc config focused_border_color  '#83a598'
bspc config pointer_modifier mod4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Xfce4-appfinder state=floating
#bspc rule -a Termite state=pseudo_tiled
bspc rule -a Gnome-terminal state=pseudo_tiled
bspc rule -a TelegramDesktop desktop='^2' state=pseudo_tiled
bspc rule -a Screenkey manage=off
bspc rule -a Wrapper-2.0 manage=off
bspc rule -a Xfce4-panel state=floating
bspc rule -a Thunar state=pseudo_tiled
