#!/usr/bin/env bash

(
    case $1 in
        (emacs) echo "rm -rf $HOME/.local/share/applications/emacs*"
                rm -rf "$HOME"/.local/share/applications/emacs*
                echo "ln -sf $HOME/.dotfiles/.local/share/applications/emacs.desktop $HOME/.local/share/applications/"
                ln -sf "$HOME"/.dotfiles/.local/share/applications/emacs.desktop "$HOME"/.local/share/applications/
                ;;
        (*)
            dotfiles_dir="$(realpath "$(dirname "$0")"/../)"

            cd "$HOME" || exit

            for file in "$HOME/.local/share/applications/emacs*"; do
                rm -f "$file"
            done

            for file in "$dotfiles_dir"/.*; do
                if [ -f "$file" ] && [ "$(basename "$file")" != ".gitignore" ]; then
                    printf "%s -> %s/%s\n" "$file" "$PWD" "$(basename "$file")"
                    ln -sf "$file" ./
                fi
            done

            for dir in ".config" ".local/bin" ".local/share/applications"; do
                mkdir -p "$HOME/$dir"
                cd "$HOME/$dir" || exit
                shopt -s dotglob

                for file in "$dotfiles_dir/$dir"/*; do
                    printf "%s -> %s/%s\n" "$file" "$PWD" "$(basename "$file")"
                    ln -sf "$file" ./
                done
            done
            ;;
        esac
)
