#!/usr/bin/env bash

(
    dotfiles_dir="$(realpath "$(dirname "$0")"/../)"

    cd "$HOME" || exit

    for file in "$dotfiles_dir"/.*; do
        if [ -f "$file" ] && [ "$(basename "$file")" != ".gitignore" ]; then
            printf "%s -> %s/%s\n" "$file" "$PWD" "$(basename "$file")"
            ln -sf "$file" ./
        fi
    done

    for dir in ".config" ".local/bin"; do
        mkdir -p "$HOME/$dir"
        cd "$HOME/$dir" || exit
        shopt -s dotglob

        for file in "$dotfiles_dir/$dir"/*; do
            printf "%s -> %s/%s\n" "$file" "$PWD" "$(basename "$file")"
            ln -sf "$file" ./
        done
    done
)
