#!/usr/bin/env sh

cd ~/Git/emacs \
    && git clean -xdf \
    && ./autogen.sh \
    && ./configure --without-compress-install \
                   --with-native-compilation=yes \
                   --with-pgtk \
                   --with-mailutils \
                   --disable-gc-mark-trace \
                   --prefix="$HOME"/.local \
                   $@ \
    && make -j$(($(nproc)-1)) \
    && make uninstall \
    && make install \
    && rm -rf "$HOME"/.local/share/applications/emacs*
