#!/usr/bin/env sh

cd ~/Git/emacs && \
    make clean \
    && ./autogen.sh \
    && ./configure \
           --without-compress-install \
           --with-native-compilation=aot \
           --with-pgtk \
           --with-mailutils \
           --prefix="$HOME"/.local $@ \
    && make -j$(($(nproc)-1)) \
    && make uninstall \
    && make install \
    && init emacs
