#!/usr/bin/env sh

while [ $# -ne 0 ]; do
    case $1 in
        (-s=*|--sep=*) separator="${1#*=}" ;;
        (--sep) shift ; separator="$1" ;;
        (--help) printf "%s\n" "sepcat -- cat with separator between files" >&2
                 printf "%s\n" "sepcat [-s=<separator>|--sep=<separator>|--sep <separator>] file1 file2 ... fileN" ;;
        (*) files="$files $1" ;;
    esac
    shift
done

for file in $files; do
    sep "$separator" "$file"
    cat "$file"
done
