;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        forward-sexp
        indent-for-tab-command
        org-self-insert-command
        org-yank
        parinfer-backward-delete-char
        parinfer-region-delete-region
        ))

(setq mc/cmds-to-run-once
      '(
        hydra-mc/body
        hydra-mc/lambda-M-s
        hydra-mc/mc/cycle-backward
        hydra-mc/mc/cycle-forward
        hydra-mc/mc/edit-ends-of-lines
        hydra-mc/mc/mark-next-like-this-word
        hydra-mc/mc/mark-next-lines
        hydra-mc/mc/mark-previous-like-this-word
        hydra-mc/mc/remove-current-cursor
        hydra-mc/mc/remove-cursors-on-blank-lines
        hydra-mc/mc/remove-duplicated-cursors
        hydra-mc/mc/remove-duplicated-cursors-and-exit
        hydra-mc/mc/vertical-align-with-space
        ))
