;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-brace
        c-electric-paren
        c-electric-semi&comma
        c-indent-line-or-region
        electric-newline-and-maybe-indent
        forward-sexp
        hydra-er/er/contract-region
        hydra-er/er/expand-region
        indent-for-tab-command
        kill-region
        my/select-line
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-fill-paragraph
        org-self-insert-command
        org-yank
        parinfer-backward-delete-char
        parinfer-double-quote
        parinfer-region-delete-region
        parinfer-semicolon
        parinfer-smart-tab:forward-char
        parinfer-smart-yank:yank
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-describe-function
        hydra-er/body
        hydra-mc/body
        hydra-mc/lambda-M-s
        hydra-mc/mc/cycle-backward
        hydra-mc/mc/cycle-forward
        hydra-mc/mc/edit-ends-of-lines
        hydra-mc/mc/mark-all-in-region-regexp
        hydra-mc/mc/mark-next-like-this-word
        hydra-mc/mc/mark-next-lines
        hydra-mc/mc/mark-previous-like-this-word
        hydra-mc/mc/remove-current-cursor
        hydra-mc/mc/remove-cursors-on-blank-lines
        hydra-mc/mc/remove-duplicated-cursors
        hydra-mc/mc/remove-duplicated-cursors-and-exit
        hydra-mc/mc/vertical-align-with-space
        minions-minor-modes-menu
        org-edit-src-save
        org-shifttab
        parinfer-mouse-drag-region
        yank-rectangle
        ))
